### Login Request to retrieve a token
POST http://localhost:4004/auth/login
Content-Type: application/json

{
  "email": "bickey@gmail.com",
  "password": "password123"
}

> {% client.global.set("token", response.body.token) %}

### UPDATE patient
PUT http://localhost:4004/api/patients/123e4567-e89b-12d3-a456-426614174000
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "John Doep0",
  "email": "john.doe@example12.com",
  "address": "123 Main St, Springfield",
  "dateOfBirth": "1985-06-15"
}