### CREATE patient
POST http://localhost:4000/patients
Content-Type: application/json

{
  "name": "JPT JPT with billing account",
  "email": "jptjptac@gmail.com",
  "address": "123 Main St, VA",
  "dateOfBirth": "1999-06-15",
  "registeredDate": "2025-08-23"
}